debug: false

server:
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MariaDB
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
